"""update db models

Revision ID: 8a3735a3fc8a
Revises: 91f86cfecbd3
Create Date: 2026-05-29 14:40:18.337393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a3735a3fc8a'
down_revision: Union[str, Sequence[str], None] = '91f86cfecbd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cwe_normalized',
    sa.Column('cwe_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('abstraction', sa.String(length=64), nullable=True),
    sa.Column('structure', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extended_description', sa.Text(), nullable=True),
    sa.Column('likelihood_of_exploit', sa.String(length=64), nullable=True),
    sa.Column('related_weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cwe_id')
    )
    op.create_table('cve_enriched',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('source_identifier', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vuln_status', sa.String(length=64), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluator_comment', sa.Text(), nullable=True),
    sa.Column('evaluator_impact', sa.Text(), nullable=True),
    sa.Column('evaluator_solution', sa.Text(), nullable=True),
    sa.Column('cvss_source', sa.Text(), nullable=True),
    sa.Column('cvss_type', sa.String(length=32), nullable=True),
    sa.Column('cvss_version', sa.String(length=16), nullable=True),
    sa.Column('cvss_vector', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('cvss_severity', sa.String(length=16), nullable=True),
    sa.Column('exploitability_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('impact_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('exploit_maturity', sa.String(length=32), nullable=True),
    sa.Column('cvss_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attack_vector', sa.String(length=32), nullable=True),
    sa.Column('attack_complexity', sa.String(length=32), nullable=True),
    sa.Column('attack_requirements', sa.String(length=32), nullable=True),
    sa.Column('privileges_required', sa.String(length=32), nullable=True),
    sa.Column('user_interaction', sa.String(length=32), nullable=True),
    sa.Column('vulnerable_confidentiality', sa.String(length=32), nullable=True),
    sa.Column('vulnerable_integrity', sa.String(length=32), nullable=True),
    sa.Column('vulnerable_availability', sa.String(length=32), nullable=True),
    sa.Column('subsequent_confidentiality', sa.String(length=32), nullable=True),
    sa.Column('subsequent_integrity', sa.String(length=32), nullable=True),
    sa.Column('subsequent_availability', sa.String(length=32), nullable=True),
    sa.Column('automatable', sa.String(length=32), nullable=True),
    sa.Column('safety', sa.String(length=32), nullable=True),
    sa.Column('recovery', sa.String(length=32), nullable=True),
    sa.Column('value_density', sa.String(length=32), nullable=True),
    sa.Column('vulnerability_response_effort', sa.String(length=32), nullable=True),
    sa.Column('provider_urgency', sa.String(length=32), nullable=True),
    sa.Column('cwe_ids', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('cwe_names', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('configurations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vendor_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('epss_score', sa.Numeric(precision=12, scale=9), nullable=True),
    sa.Column('epss_percentile', sa.Numeric(precision=12, scale=9), nullable=True),
    sa.Column('epss_score_date', sa.Date(), nullable=True),
    sa.Column('is_kev', sa.Boolean(), nullable=False),
    sa.Column('kev_vendor_project', sa.Text(), nullable=True),
    sa.Column('kev_product', sa.Text(), nullable=True),
    sa.Column('kev_vulnerability_name', sa.Text(), nullable=True),
    sa.Column('kev_date_added', sa.Date(), nullable=True),
    sa.Column('kev_due_date', sa.Date(), nullable=True),
    sa.Column('kev_required_action', sa.Text(), nullable=True),
    sa.Column('kev_short_description', sa.Text(), nullable=True),
    sa.Column('kev_notes', sa.Text(), nullable=True),
    sa.Column('ransomware_known', sa.String(length=32), nullable=True),
    sa.Column('kev_cwes', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('nvd_cisa_exploit_add', sa.Date(), nullable=True),
    sa.Column('nvd_cisa_action_due', sa.Date(), nullable=True),
    sa.Column('nvd_cisa_required_action', sa.Text(), nullable=True),
    sa.Column('nvd_cisa_vulnerability_name', sa.Text(), nullable=True),
    sa.Column('raw_nvd_s3_key', sa.Text(), nullable=True),
    sa.Column('raw_epss_s3_key', sa.Text(), nullable=True),
    sa.Column('raw_kev_s3_key', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_transform_run_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cvss_score IS NULL OR (cvss_score >= 0 AND cvss_score <= 10)', name='ck_cve_cvss_score_range'),
    sa.CheckConstraint('epss_percentile IS NULL OR (epss_percentile >= 0 AND epss_percentile <= 1)', name='ck_cve_epss_percentile_range'),
    sa.CheckConstraint('epss_score IS NULL OR (epss_score >= 0 AND epss_score <= 1)', name='ck_cve_epss_score_range'),
    sa.ForeignKeyConstraint(['last_transform_run_id'], ['elt_runs.id'], ),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_index(op.f('ix_cve_enriched_attack_vector'), 'cve_enriched', ['attack_vector'], unique=False)
    op.create_index(op.f('ix_cve_enriched_automatable'), 'cve_enriched', ['automatable'], unique=False)
    op.create_index(op.f('ix_cve_enriched_cvss_score'), 'cve_enriched', ['cvss_score'], unique=False)
    op.create_index(op.f('ix_cve_enriched_cvss_severity'), 'cve_enriched', ['cvss_severity'], unique=False)
    op.create_index(op.f('ix_cve_enriched_cvss_version'), 'cve_enriched', ['cvss_version'], unique=False)
    op.create_index(op.f('ix_cve_enriched_epss_percentile'), 'cve_enriched', ['epss_percentile'], unique=False)
    op.create_index(op.f('ix_cve_enriched_epss_score'), 'cve_enriched', ['epss_score'], unique=False)
    op.create_index(op.f('ix_cve_enriched_exploit_maturity'), 'cve_enriched', ['exploit_maturity'], unique=False)
    op.create_index(op.f('ix_cve_enriched_is_kev'), 'cve_enriched', ['is_kev'], unique=False)
    op.create_index(op.f('ix_cve_enriched_kev_date_added'), 'cve_enriched', ['kev_date_added'], unique=False)
    op.create_index(op.f('ix_cve_enriched_kev_due_date'), 'cve_enriched', ['kev_due_date'], unique=False)
    op.create_index(op.f('ix_cve_enriched_last_modified_at'), 'cve_enriched', ['last_modified_at'], unique=False)
    op.create_index('ix_cve_enriched_priority', 'cve_enriched', ['is_kev', 'cvss_severity', 'epss_percentile'], unique=False)
    op.create_index(op.f('ix_cve_enriched_privileges_required'), 'cve_enriched', ['privileges_required'], unique=False)
    op.create_index(op.f('ix_cve_enriched_published_at'), 'cve_enriched', ['published_at'], unique=False)
    op.create_index(op.f('ix_cve_enriched_ransomware_known'), 'cve_enriched', ['ransomware_known'], unique=False)
    op.create_index('ix_cve_enriched_status_modified', 'cve_enriched', ['vuln_status', 'last_modified_at'], unique=False)
    op.create_index(op.f('ix_cve_enriched_user_interaction'), 'cve_enriched', ['user_interaction'], unique=False)
    op.create_index(op.f('ix_cve_enriched_vuln_status'), 'cve_enriched', ['vuln_status'], unique=False)
    op.create_table('cwe_fetch_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cwe_id', sa.String(length=32), nullable=False),
    sa.Column('requested_by_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'success', 'failed')", name='ck_cwe_fetch_jobs_status'),
    sa.ForeignKeyConstraint(['requested_by_run_id'], ['elt_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cwe_id', 'status', name='uq_cwe_fetch_jobs_cwe_status')
    )
    op.create_index(op.f('ix_cwe_fetch_jobs_cwe_id'), 'cwe_fetch_jobs', ['cwe_id'], unique=False)
    op.create_index(op.f('ix_cwe_fetch_jobs_status'), 'cwe_fetch_jobs', ['status'], unique=False)
    op.create_table('raw_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('elt_run_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('pass_name', sa.String(length=32), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('start_index', sa.Integer(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('source_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('nvd_cves', 'nvd_changes', 'epss', 'cisa_kev', 'cwe', 'transform', 'load', 'consistency', 'recovery', 'watchdog', 'system')", name='ck_raw_artifacts_source'),
    sa.ForeignKeyConstraint(['elt_run_id'], ['elt_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index('ix_raw_artifacts_run_source', 'raw_artifacts', ['elt_run_id', 'source'], unique=False)
    op.create_index('ix_raw_artifacts_source_page', 'raw_artifacts', ['source', 'page_number'], unique=False)
    op.create_table('cve_consistency',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('elt_run_id', sa.UUID(), nullable=False),
    sa.Column('nvd_ok', sa.Boolean(), nullable=False),
    sa.Column('cvss_resolved', sa.Boolean(), nullable=False),
    sa.Column('epss_ok', sa.Boolean(), nullable=False),
    sa.Column('kev_ok', sa.Boolean(), nullable=False),
    sa.Column('overall_ok', sa.Boolean(), sa.Computed('(nvd_ok AND cvss_resolved AND epss_ok AND kev_ok)', persisted=True), nullable=True),
    sa.Column('failure_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cve_id'], ['cve_enriched.cve_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['elt_run_id'], ['elt_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cve_id', 'elt_run_id')
    )
    op.create_index('ix_cve_consistency_cve_overall', 'cve_consistency', ['cve_id', 'overall_ok'], unique=False)
    op.create_index('ix_cve_consistency_run_overall', 'cve_consistency', ['elt_run_id', 'overall_ok'], unique=False)
    op.create_table('cve_cvss_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('elt_run_id', sa.UUID(), nullable=False),
    sa.Column('old_version', sa.String(length=16), nullable=True),
    sa.Column('new_version', sa.String(length=16), nullable=True),
    sa.Column('old_vector', sa.Text(), nullable=True),
    sa.Column('new_vector', sa.Text(), nullable=True),
    sa.Column('old_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('new_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('old_severity', sa.String(length=16), nullable=True),
    sa.Column('new_severity', sa.String(length=16), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cve_id'], ['cve_enriched.cve_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['elt_run_id'], ['elt_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cve_cvss_history_cve_changed', 'cve_cvss_history', ['cve_id', 'changed_at'], unique=False)
    op.create_table('cve_kev_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('elt_run_id', sa.UUID(), nullable=False),
    sa.Column('field_changed', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('cisa_kev', 'nvd_cves', 'nvd_changes')", name='ck_cve_kev_history_source'),
    sa.ForeignKeyConstraint(['cve_id'], ['cve_enriched.cve_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['elt_run_id'], ['elt_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cve_kev_history_cve_changed', 'cve_kev_history', ['cve_id', 'changed_at'], unique=False)
    op.create_table('cve_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('elt_run_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=64), nullable=True),
    sa.Column('new_status', sa.String(length=64), nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cve_id'], ['cve_enriched.cve_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['elt_run_id'], ['elt_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cve_status_history_cve_changed', 'cve_status_history', ['cve_id', 'changed_at'], unique=False)
    op.create_table('cve_weaknesses',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('cwe_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cve_id'], ['cve_enriched.cve_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cwe_id'], ['cwe_normalized.cwe_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cve_id', 'cwe_id')
    )
    op.create_index('ix_cve_weaknesses_cwe', 'cve_weaknesses', ['cwe_id'], unique=False)
    op.create_table('epss_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('elt_run_id', sa.UUID(), nullable=True),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('epss_score', sa.Numeric(precision=12, scale=9), nullable=False),
    sa.Column('percentile', sa.Numeric(precision=12, scale=9), nullable=False),
    sa.Column('raw_s3_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('epss_score >= 0 AND epss_score <= 1', name='ck_epss_scores_score_range'),
    sa.CheckConstraint('percentile >= 0 AND percentile <= 1', name='ck_epss_scores_percentile_range'),
    sa.ForeignKeyConstraint(['cve_id'], ['cve_enriched.cve_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['elt_run_id'], ['elt_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cve_id', 'score_date', name='uq_epss_scores_cve_date')
    )
    op.create_index('ix_epss_scores_date_score', 'epss_scores', ['score_date', 'epss_score'], unique=False)
    op.add_column('elt_runs', sa.Column('mode', sa.String(length=32), nullable=False))
    op.add_column('elt_runs', sa.Column('pipeline', sa.String(length=32), nullable=True))
    op.add_column('elt_runs', sa.Column('current_phase', sa.String(length=64), nullable=True))
    op.add_column('elt_runs', sa.Column('advisory_lock_key', sa.Integer(), nullable=True))
    op.add_column('elt_runs', sa.Column('expected_max_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('elt_runs', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('elt_runs', sa.Column('skipped_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('elt_runs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('elt_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('elt_runs', 'sources_status',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_elt_runs_status'), 'elt_runs', ['status'], unique=False)
    op.add_column('pipeline_logs', sa.Column('cve_id', sa.String(length=32), nullable=True))
    op.add_column('pipeline_logs', sa.Column('phase', sa.String(length=64), nullable=True))
    op.add_column('pipeline_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('pipeline_logs', 'level',
               existing_type=postgresql.ENUM('INFO', 'WARNING', 'ERROR', name='log_level'),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('pipeline_logs', 'source',
               existing_type=postgresql.ENUM('nvd_cves', 'nvd_changes', 'epss', 'cisa_kev', 'system', name='log_source'),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('pipeline_logs', 'event_type',
               existing_type=postgresql.ENUM('fetch_start', 'fetch_success', 'retry_attempt', 'fetch_failed', 'fallback_triggered', 'store_success', name='event_type'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('pipeline_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_pipeline_logs_created_at'), 'pipeline_logs', ['created_at'], unique=False)
    op.create_index('ix_pipeline_logs_run_cve_event', 'pipeline_logs', ['elt_run_id', 'cve_id', 'event_type'], unique=False)
    op.create_index('ix_pipeline_logs_run_event', 'pipeline_logs', ['elt_run_id', 'event_type'], unique=False)
    op.create_index('ix_pipeline_logs_source_created', 'pipeline_logs', ['source', 'created_at'], unique=False)
    op.drop_constraint('pipeline_logs_elt_run_id_fkey', 'pipeline_logs', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_logs', 'elt_runs', ['elt_run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_logs', 'cve_enriched', ['cve_id'], ['cve_id'], ondelete='SET NULL')
    op.drop_column('pipeline_logs', 'extra')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_logs', sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pipeline_logs', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_logs', type_='foreignkey')
    op.create_foreign_key('pipeline_logs_elt_run_id_fkey', 'pipeline_logs', 'elt_runs', ['elt_run_id'], ['id'])
    op.drop_index('ix_pipeline_logs_source_created', table_name='pipeline_logs')
    op.drop_index('ix_pipeline_logs_run_event', table_name='pipeline_logs')
    op.drop_index('ix_pipeline_logs_run_cve_event', table_name='pipeline_logs')
    op.drop_index(op.f('ix_pipeline_logs_created_at'), table_name='pipeline_logs')
    op.alter_column('pipeline_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('pipeline_logs', 'event_type',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('fetch_start', 'fetch_success', 'retry_attempt', 'fetch_failed', 'fallback_triggered', 'store_success', name='event_type'),
               existing_nullable=False)
    op.alter_column('pipeline_logs', 'source',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('nvd_cves', 'nvd_changes', 'epss', 'cisa_kev', 'system', name='log_source'),
               existing_nullable=False)
    op.alter_column('pipeline_logs', 'level',
               existing_type=sa.String(length=16),
               type_=postgresql.ENUM('INFO', 'WARNING', 'ERROR', name='log_level'),
               existing_nullable=False)
    op.drop_column('pipeline_logs', 'metadata')
    op.drop_column('pipeline_logs', 'phase')
    op.drop_column('pipeline_logs', 'cve_id')
    op.drop_index(op.f('ix_elt_runs_status'), table_name='elt_runs')
    op.alter_column('elt_runs', 'sources_status',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('elt_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('elt_runs', 'metadata')
    op.drop_column('elt_runs', 'skipped_sources')
    op.drop_column('elt_runs', 'last_heartbeat_at')
    op.drop_column('elt_runs', 'expected_max_duration_minutes')
    op.drop_column('elt_runs', 'advisory_lock_key')
    op.drop_column('elt_runs', 'current_phase')
    op.drop_column('elt_runs', 'pipeline')
    op.drop_column('elt_runs', 'mode')
    op.drop_index('ix_epss_scores_date_score', table_name='epss_scores')
    op.drop_table('epss_scores')
    op.drop_index('ix_cve_weaknesses_cwe', table_name='cve_weaknesses')
    op.drop_table('cve_weaknesses')
    op.drop_index('ix_cve_status_history_cve_changed', table_name='cve_status_history')
    op.drop_table('cve_status_history')
    op.drop_index('ix_cve_kev_history_cve_changed', table_name='cve_kev_history')
    op.drop_table('cve_kev_history')
    op.drop_index('ix_cve_cvss_history_cve_changed', table_name='cve_cvss_history')
    op.drop_table('cve_cvss_history')
    op.drop_index('ix_cve_consistency_run_overall', table_name='cve_consistency')
    op.drop_index('ix_cve_consistency_cve_overall', table_name='cve_consistency')
    op.drop_table('cve_consistency')
    op.drop_index('ix_raw_artifacts_source_page', table_name='raw_artifacts')
    op.drop_index('ix_raw_artifacts_run_source', table_name='raw_artifacts')
    op.drop_table('raw_artifacts')
    op.drop_index(op.f('ix_cwe_fetch_jobs_status'), table_name='cwe_fetch_jobs')
    op.drop_index(op.f('ix_cwe_fetch_jobs_cwe_id'), table_name='cwe_fetch_jobs')
    op.drop_table('cwe_fetch_jobs')
    op.drop_index(op.f('ix_cve_enriched_vuln_status'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_user_interaction'), table_name='cve_enriched')
    op.drop_index('ix_cve_enriched_status_modified', table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_ransomware_known'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_published_at'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_privileges_required'), table_name='cve_enriched')
    op.drop_index('ix_cve_enriched_priority', table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_last_modified_at'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_kev_due_date'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_kev_date_added'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_is_kev'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_exploit_maturity'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_epss_score'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_epss_percentile'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_cvss_version'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_cvss_severity'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_cvss_score'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_automatable'), table_name='cve_enriched')
    op.drop_index(op.f('ix_cve_enriched_attack_vector'), table_name='cve_enriched')
    op.drop_table('cve_enriched')
    op.drop_table('cwe_normalized')
    # ### end Alembic commands ###
