"""create pipeline_logs table

Revision ID: 91f86cfecbd3
Revises: 86f38fc60d68
Create Date: 2026-05-01 18:39:37.413544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f86cfecbd3'
down_revision: Union[str, Sequence[str], None] = '86f38fc60d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('elt_run_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', name='log_level'), nullable=False),
    sa.Column('source', sa.Enum('nvd_cves', 'nvd_changes', 'epss', 'cisa_kev', 'system', name='log_source'), nullable=False),
    sa.Column('event_type', sa.Enum('fetch_start', 'fetch_success', 'retry_attempt', 'fetch_failed', 'fallback_triggered', 'store_success', name='event_type'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['elt_run_id'], ['elt_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_logs')
    # ### end Alembic commands ###
